### PR TITLE
Added to the README file

### PR DESCRIPTION
**Pull request by avneesh0612**
Added my name and Github account

### CODE REVIEW

**Comment by gmagnenat** [comment]
Looking good. 👍 nice job.

**Review by gmagnenat — APPROVED** [review]
All good. Thanks for the PR

**Comment by avneesh0612** [comment]
> Looking good. 👍 nice job.

Thank you 😊

**Comment by avneesh0612** [comment]
> All good. Thanks for the PR

I want to thank you got to learn something new

**Pull request merged**
